# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the file requirement
ADD requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN apt-get update
RUN apt-get install -y python-pip python-dev libmysqlclient-dev
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Set the working directory to /twitter
WORKDIR /twitter

# Copy the current directory contents into the container at /app
ADD ./python-code /twitter

# Define environment variable
ENV MYSQL_DB_HOST MYSQL_ROOT_PASSWORD MYSQL_DATABASE MYSQL_USER

# Run app.py when the container launches
CMD ["python", "app.py"]
